In [22]:
import pandas as pd
group_ds = pd.read_csv("Language&Tags.csv")
og_github_twitch = pd.read_csv("10.05.2021.13.04LABELS.csv")

In [23]:
#switching "ID" in og twitch to say "Channel_Name" so it's the same name as group work
og_github_twitch.rename(columns={'ID': 'Channel_Name'}, inplace=True)
og_github_twitch

og_github_twitch = og_github_twitch.sort_values(by='Channel_Name', ascending=True)
og_github_twitch

       Channel_Name          Label   Count
1939         01bd02         01bd02    9494
1185      10000DAYS      10000DAYS   11781
450          109ace         109ace   30832
1801        17BLAZX        17BLAZX   17744
1111       1DrakoNz       1DrakoNz   18974
...             ...            ...     ...
150       zwebackhd      zwebackhd   16068
1187       zxcursed       zxcursed  100918
363           zybbr          zybbr    4038
1707         zynxyz         zynxyz    5238
1415  zzamtiger0310  zzamtiger0310   19246

[2200 rows x 3 columns]

In [19]:
#merging the count using the channel names/ ID; using left join
# left_combined_w_count = pd.merge(group_ds, og_github_twitch[["Channel_Name", "Count"]], on='Channel_Name', how='left')
# left_combined_w_count

#attempting inner merge for og df
df_inner = pd.merge(group_ds, og_github_twitch[["Channel_Name", "Count"]], on='Channel_Name', how='inner')
df_inner

,Channel_Name,Language,Tags,Last Played Game,Game ID,Count
0,alelu,ja,"['日本語', 'apex', '雑談']",Apex Legends,511224,13509
1,alanzoka,pt,"['Idoso', 'Gostoso', 'Português']",Just Chatting,509658,201431
2,alenenwooptv,ko,['한국어'],Just Chatting,509658,9914
3,alexelcapo,es,['Español'],Special Events,509663,93758
4,aminematue,fr,['Français'],Just Chatting,509658,52468
...,...,...,...,...,...,...
614,zynxyz,zh,"['japanese', '中文']",Minecraft,27471,5238
615,yoshinama222,ja,"['日本語', '匂わせ禁止', 'ネタバレ禁止', 'ネタバレ注意']",Pawafuru Puro Yakyuu 2024-2025,1183847148,11925
616,yuniko0720,zh,['中文'],Minds Beneath Us,1569955542,16809
617,zombs,en,['English'],VALORANT,516575,27356
618,zunksoyyo,es,"['Español', 'Roleplay']",Just Chatting,509658,5439